name: Docker Image CI

on:
  push:
    branches: [ gcc-12 ]
  pull_request:
    branches: [ gcc-12 ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/vsysoev/gcc-cmake-gdb:latest
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        # registry: docker.pkg.github.com
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Publish the latest Docker image
      run: docker push ghcr.io/vsysoev/gcc-cmake-gdb:latest
